spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    # url: jdbc:oracle:thin:@localhost:1521:ORCL
    # url: jdbc:oracle:thin:@192.168.0.51:1521/ORCL
    url: jdbc:oracle:thin:@192.168.0.119:1521/xe
    username: drt
    password: drt123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
     maximum-pool-size: 20
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  config:
    location: currentdir/config

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    default-fetch-size: 500
    
server:
  port: 9999
  tomcat:
    additional-tld-skip-patterns:  "*.jar"

