spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.51:1521/ORCL
    username: drt
    password: drt123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    default-fetch-size: 500

server:
  tomcat:
    additional-tld-skip-patterns:  "*.jar"